name: scheduler

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

permissions:
  contents: write

jobs:
  scheduler:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run scheduler
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
          PENDING_FOLDER_ID: ${{ secrets.PENDING_FOLDER_ID }}
          SCHEDULED_FOLDER_ID: ${{ secrets.SCHEDULED_FOLDER_ID }}
        run: node scripts/scheduler.js

      - name: Commit dashboard updates
        run: |
          git config --global user.name "scheduler-bot"
          git config --global user.email "scheduler@bot.com"
          git add scheduler-status.json
          git add last_schedule_date.json
          git commit -m "update scheduler status" || echo "No changes"
          git push
