name: YouTube Scheduler

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  scheduler:

    runs-on: ubuntu-latest

    env:
      PENDING_FOLDER_ID: ${{ secrets.PENDING_FOLDER_ID }}
      SCHEDULED_FOLDER_ID: ${{ secrets.SCHEDULED_FOLDER_ID }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run scheduler
        run: node scripts/scheduler.js
